// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI81Yy74GDrQShLhYkOHTn3jhjMh2nGY8',
    appId: '1:888561835044:android:62a3312e13ddee71924cb1',
    messagingSenderId: '888561835044',
    projectId: 'sih-23',
    databaseURL: 'https://sih-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sih-23.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC14ean1YYS-0IV0VzkPZS4cbYGm5TLhzI',
    appId: '1:888561835044:ios:c5a2ff8477b6ca7d924cb1',
    messagingSenderId: '888561835044',
    projectId: 'sih-23',
    databaseURL: 'https://sih-23-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sih-23.appspot.com',
    androidClientId: '888561835044-kmr16ibgt2fjn97s6tauv82262ousema.apps.googleusercontent.com',
    iosClientId: '888561835044-q6e55cpob9p4afiqrlu63j5ulplgcbof.apps.googleusercontent.com',
    iosBundleId: 'com.example.userMitti',
  );
}
